### ISSUE TITLE
Compressed Audio + Bass Enhancing + Perfect EQ - sounds weird now

### ISSUE THREAD

**Issue by flipwise** [JackHack96/PulseEffects-Presets#1]
Hey there,

first of all thanks for your presets, they've greatly increased my audio experience in Linux.

I just wanted to leave my observation that after Pulse effect switched to calf for certain effects in 3.2.2 the Compressed Audio + Bass Enhancing + Perfect EQ present has a weird reverb sound to it. 

I am not sure if it's just me, but it can be fixed by turning of the input limiter. Might also mean some of the settings need to be adjusted.

**Comment by JackHack96** [comment]
Interesting, thank for reporting the issue, now I'll correct it :grin:

**Comment by flipwise** [comment]
Hey, I realized today in pavucontrol that a pulseeffect stream had its volume set to low and when I restored it to 100% the input limiter is just fine now. Maybe I made a mistake when I reported this then and it's not an issue.

**Comment by JackHack96** [comment]
Well, the difference is not that much... So I'll leave it as it's now

**Comment by flipwise** [comment]
Yeah, I'm not sure whether to use it myself or not honestly. 

BTW, from version 4.0 pulseeffects now uses .json for presets: https://github.com/wwmm/pulseeffects/blob/master/CHANGELOG.md
