### ISSUE TITLE
PulseEffecet is replaced with EasyEffects

### ISSUE THREAD

**Issue by iKeramat** [JackHack96/PulseEffects-Presets#14]
As PulseEffecet replaced with EasyEffects, please fix configs with EasyEffects.
https://github.com/wwmm/easyeffects

**Comment by JackHack96** [comment]
Oh I just checked it now! I was aware that Wallace replaced the PulseAudio interface with the PipeWire one, but I didn't know that he also changed the name!
I'm on Ubuntu 20.04 right now with a working PulseAudio stack + older PulseEffects 4. I see that I can upgrade to PipeWire through a PPA (though it's risky), so I'll see if I can upgrade and test everything in the weekend.

**Comment by iKeramat** [comment]
switch to arch bruh😂😂

**Comment by MasterKia** [comment]
Could you fix this issue?
I need to activate Dolby Atmos effects.

**Comment by deifactor** [comment]
You can download the json files, run this script over them, and then install them manually. Making the installer do this will be a bit harder.

(Note that the manual method also doesn't copy over impulse files.)

```sh
#!/bin/sh

# Replace with 'input' if you want to convert input preset
section='output'

# Convert boolean and numeric strings + replace invalid empty blocklist
perl -i -pe 's/"(true|false|[\d\.-]+)"/$1/g; s/(?<="bl(a|o)cklist": )""/[]/g' "$@"

# Fix plugins order using v5 state field (your set up plugin order is preserved)
for f in "$@"; do

  # Extract active plugins in right order
  po_src=$(jq ".$section"' | . as $out | .plugins_order | .[] | . as $pn | select($out | to_entries | .[] | .key as $key | select(["blocklist", "blacklist", "plugins_order"] | any(. == $key) | not) | select(.value.state != false) | .key == $pn)' "$f" -r)

  # Replace order array in config with new one
  jq --arg po "$po_src" '($po | split("\n")) as $poa | '".$section.plugins_order"' = $poa' "$f" >tmp
  mv tmp "$f"
done
```

The original script is by AbsurdlySuspicious, I just tweaked it a bit to account for "blacklist" vs "blocklist". My version, like the original, is CC0 (so do whatever the hell you want with it).

**Comment by JackHack96** [comment]
Hey so yesterday I've installed PipeWire and I'm currently testing it with EasyEffetcs. There is an issue with chopping audio under heavy load (e.g. when I'm compiling) which didn't happened using PulseAudio, but I suspect this is more likely to be caused by the fact that Ubuntu 20.04 wasn't built with PipeWire by default (I installed it through the PPA).
Anyway now I'll rewrite the presets so that you can use them out-of-the-box :)

**Comment by JackHack96** [comment]
I've uploaded the updated presets and the updated script, let me know if everything works :)

**Comment by LittleHuba** [comment]
Just installed it on an up-to-date ArchLinux installation with PipeWire and EasyEffects. Works as expected.
