### ISSUE TITLE
Permanent hardware damage

### ISSUE THREAD

**Issue by agoodm88** [JackHack96/PulseEffects-Presets#16]
I have a ThinkPad X1 Carbon Gen 9. I installed pulse effects from apt along with presets from here https://github.com/JackHack96/PulseEffects-Presets

I selected convolva and then chose the Dolby Atmos preset. I started playing music on Spotify and turned up the volume a bit. I heard a slight bit of distortion and then one of the speakers on the bottom of the laptop stopped working.  It appears that I pretty much instantly caused permanent damage to my laptop. I've tested the speakers using a live boot disk and they don't work there either.

I didn't see any warnings about hardware damage and honestly thought I'd hear sounds if distress long before anything broke.  So user beware I guess?!

**Comment by JackHack96** [comment]
I'm sorry for the damage, but I'm not sure if an audio effects software can damage the speakers (I'm not an hardware engineer though).
