### ISSUE TITLE
Translation from .preset to .json

### ISSUE THREAD

**Issue by mzannoni** [JackHack96/PulseEffects-Presets#2]
From version 4 of PulseEffect, the preset format has been completely changed, and it's not back compatible.
The preset currently in the repo are not usable anymore.
Is it planned to translate them to json format or everybody should take care of it on it's own?

**Comment by JackHack96** [comment]
I know, but I assure you I'm going to translate the presets to JSON (I hope I'll do it during this week)

**Comment by mzannoni** [comment]
That's great to hear, thanks!
And no hurry, of course ;-)

Looking at the json after saving an preset, they seem similar, with some main difference. I was actually thinking if it may make sense to create a script for automated translation, but I'm not sure if it's worth it.
I've also noted that now in the json file the effects are organized into "input" and "output", istead of having "app-" or "mic_" in the name.

**Comment by JackHack96** [comment]
I've managed to publish one preset. I had to use a limiter to prevent audio clipping, because I can't find the master channel on the equalizer.
Now I'm full of exams, so I can't spend much time on adjusting it, but when the exam session will finish I'll further investigate on how to improve the presets :)

**Comment by mzannoni** [comment]
Thanks a lot, and good luck for the exams!

I've tried a bit, and I disabled the Limiter, since it actually distorts a bit (it limits volume peaks, not linearly).
To control clipping I used instead the master Input and Output of the Bass Enhancer, and it seems to work ok for now.
I really hope they bring back the master channels to the equalizer, though...

**Comment by oblivionnewtonjohn** [comment]
I am running Solus distro, running PulseEffects 3.2.3 and cannot locate the presets folder. 
I attempted to search for the four I have created as a way to identify the path, no luck. 

Any suggestions?

**Comment by JackHack96** [comment]
Mmmh, I never used Solus, as far as I know it uses a custom package format.
Anyway, have you tried searching with `find . -name "PulseEffects"`? Try running the command in your home directory :)

**Comment by mzannoni** [comment]
I normally use the 'locate' command for this kind of task (make sure your 'updatedb' is run periodically, which should be, but I'm not familiar with Solus).

**Comment by JackHack96** [comment]
The next release of PulseEffects has a master channel control! Whenever I'll receive the update I'll update the preset ;)

**Comment by JackHack96** [comment]
Ok, I've updated the presets accordingly, let me know if it's all good ;)
