### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by GoodGuyNick** [JackHack96/PulseEffects-Presets#3]
@JackHack96 I just want to say **THANK YOU**. For two years I was suffering with shitty sound because of Beats Audio and nothing helped when I tried to fix it. But today I've installed PulseEffects and imported yours presets, and I'm no longer suffering from shitty sound.

**Comment by JackHack96** [comment]
I'm glad it helped you!

**Comment by BobbyWibowo** [comment]
I'll ride on this issue to also say a personal thank you (cause it's already closed).

All of the settings in wwmm's PulseEffects legit made absolutely zero sense to me.
Despite wanting to improve my listening experience, I don't understand sound effects at all.
So I just spent aplenty on quality headphones and earbuds, and I simply assumed those would be the best quality that I could ever achieve; unless I wanted to fork out more for one of those for-professional gears or whatever.

So I was also somewhat glad there were community presets available (and linked in the repo's wiki).
Honestly, I wouldn't have bothered trying PulseEffects if there were no presets cause I would have no idea where to start anyway.
Like, even after seeing this repo, I was like, "What the frick is Convolver? ... IRS? What?".

And after trying Bass Enhancing + Perfect EQ from this repo, honestly I was like,... holy guacamole!
I feel like I've missed A LOT in the past few years. I repeat, A LOT!

So yeah, I wanna say thank you very much for these presets! 🙏

Like, I understand that wwmm's huge efforts on PulseEffects also made this possible.
But it's like one those sayings y'know, that even the most useful of things would simply become useless in the hands of those who coulnd't realize their true values, or something along that line..
