### ISSUE TITLE
"Bass Enhancing + Perfect EQ.json" needs adapting after installation to new /home/{user} folder for .irs settings

### ISSUE THREAD

**Issue by kernelOfTruth** [JackHack96/PulseEffects-Presets#4]
FYI: By default the path is set to

`` "kernel-path": "\/home\/matteo\/.config\/PulseEffects\/irs\/Dolby ATMOS ((128K MP3)) 1.Default.irs", ``

so the Convolver part will not work - also I had to select one of the irs profiles in the Convolver part of the app to make it work.

In a nutshell:

Just select the irs profiles in the Convolver part of the Application via the "impulse response file" setting (the wave form button) the first time you launch it - and it should be fine,

Great settings ! - loving the irs files - never had this great sound output on Linux so far <3

Thanks

**Comment by JackHack96** [comment]
Wops, I forgot about that xD
Maybe I could use `sed` in the installation script for automatically adjust the path :)
