### ISSUE TITLE
Irs file not loading

### ISSUE THREAD

**Issue by Hedronmx** [JackHack96/PulseEffects-Presets#6]
I get the following error
`(pulseeffects:15704): pulseeffects-DEBUG: 04:51:34.786: convolver: irs file does not exists or it is empty: 
(pulseeffects:15704): pulseeffects-DEBUG: 04:51:34.786: convolver: we will just passthrough data.
(pulseeffects:15704): pulseeffects-DEBUG: 04:51:34.798: sie: convolver is disabled
`
Eventhough I have the files inside ~./config/PulseEffects/irs/.
I even tried loading them through the gui.

**Comment by Utini2000** [comment]
And I am not exactly sure how to load the .irs files?  
My laptop comes in Windows with Dolby Atmos installed and it changes the sound signature of my speakers a lot.  
I wanted to get the same effect in linux and installed pulseeffects + downloaded your presets and the .irs files. But how do I activate the dolby atmos .irs file?

**Comment by JackHack96** [comment]
@Utini2000 You have to place the `.irs` files inside your `PulseEffects` directory.
Then open PulseEffects, go in the Convolver plugin and enable it.
Click this button
![image](https://user-images.githubusercontent.com/3611330/50540635-c7b3e900-0b95-11e9-85b0-cb32cea586bf.png)
and select the impulse response you want (BTW I'm going to add some other high quality impulse responses I use on my smartphone)

@Hedronmx It seems the convolver is not enabled, try enabling it first

**Comment by Utini2000** [comment]
@JackHack96 
Awesome thank you.. I instantly loved the sound of my laptops speakers on Windows with the Dolby Atmos effect. 
Now I can finally enjoy this sound on Linux as well :)  

Is there a way to change the preset (like the overall and complete preset of all pulseeffect settings) depending on which output is active in pulseaudio?  
E.g. Dolby Atmos for Speaker and my own preset when I connect my external DAC/AMP/Headphones?

**Comment by JackHack96** [comment]
As far as I know there's currently no way of having that behaviour.
You could open a feature request upstream :+1:

**Comment by Utini2000** [comment]
Thanks again :) Done so:
https://github.com/wwmm/pulseeffects/issues/398
