### ISSUE TITLE
Paths with flatpak

### ISSUE THREAD

**Issue by timojuez** [JackHack96/PulseEffects-Presets#9]
Hi,

The Convolver does not find files if PulseEffects is being installed with flatpak. The actual path will be ~/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/irs while ~/.config/PulseEffects/irs is not permitted by default for security reasons and sandboxing. The install script should adjust it. Maybe there is an option to detect PulseEffect's correct path or use some magic variable for the config path?

**Comment by JackHack96** [comment]
I'm using Flatpak Pulseeffects and it works...
The script first check if the Flatpak version is installed, if so it's install them in `~/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/irs`.
If it doesn't find the Flatpak, it installs them in `~/.config/PulseEffects/irs`.

After that, you just have to open PulseEffects, go in the convolver tab and select one of them :)

**Comment by timojuez** [comment]
Hm, looks gut. Maybe I had native PulseEffects and then upgraded to the flatpak version
